import { parseMessageContent } from "./fields.ts";
import type { MessageSender } from "./fields.ts";

/**
 * Token usage estimation utility.
 *
 * Categorizes messages into buckets:
 *   input_tokens:    human messages, tool_result
 *   output_tokens:   assistant_text, tool_use
 *   thinking_tokens: thinking (reasoning blocks)
 *
 * Estimation formulas (when no API usage object available):
 *   prose   → len / 4
 *   code    → len / 3
 *   json    → len / 3.5
 */

// ─── Types ───────────────────────────────────────────────────────────────────

export interface TokenBucket {
  input: number;
  output: number;
  thinking: number;
}

export interface ConversationTokenUsage extends TokenBucket {
  total: number;
  messageCount: number;
}

export interface ApplicationTokenUsage extends TokenBucket {
  total: number;
  conversationCount: number;
}

export interface MessageTokenInfo {
  bucket: "input" | "output" | "thinking";
  tokens: number;
}

// ─── Estimation Functions ────────────────────────────────────────────────────

/** Estimate tokens for general prose (human text, assistant responses) */
function estimateProse(text: string): number {
  return Math.ceil(text.length / 4);
}

/** Estimate tokens for code or tool output (denser content) */
function estimateCode(text: string): number {
  return Math.ceil(text.length / 3);
}

/** Estimate tokens for structured data (JSON, tool call parameters) */
function estimateJson(text: string): number {
  return Math.ceil(text.length / 3.5);
}

/**
 * Detect content type and apply the appropriate estimation formula.
 */
function estimateTokens(text: string, sender: MessageSender): number {
  if (!text) return 0;

  switch (sender) {
    case "user":
      return estimateProse(text);
    case "assistant":
      return estimateProse(text);
    case "assistant-thinking":
      return estimateProse(text);
    case "assistant-tool":
      // Tool calls tend to be JSON/code-like
      return looksLikeJson(text) ? estimateJson(text) : estimateCode(text);
    default:
      return estimateProse(text);
  }
}

/** Simple heuristic to detect JSON-like content */
function looksLikeJson(text: string): boolean {
  const trimmed = text.trim();
  return (trimmed.startsWith("{") && trimmed.endsWith("}")) ||
         (trimmed.startsWith("[") && trimmed.endsWith("]"));
}

// ─── Bucket Assignment ───────────────────────────────────────────────────────

/**
 * Determine which token bucket a message sender maps to.
 *
 * Mapping:
 *   user              → input  (human messages enter the model as input)
 *   assistant         → output (generated text by the model)
 *   assistant-thinking→ thinking (generated, tracked separately)
 *   assistant-tool    → output (tool_use calls generated by the model)
 */
function senderToBucket(sender: MessageSender): "input" | "output" | "thinking" {
  switch (sender) {
    case "user":
      return "input";
    case "assistant":
      return "output";
    case "assistant-thinking":
      return "thinking";
    case "assistant-tool":
      return "output";
    default:
      return "input";
  }
}

// ─── Public API ──────────────────────────────────────────────────────────────

/**
 * Analyze a single message and return its token info.
 */
export function analyzeMessage(msg: any): MessageTokenInfo | null {
  const parsed = parseMessageContent(msg.content);
  if (!parsed) return null;

  const bucket = senderToBucket(parsed.sender);
  const tokens = estimateTokens(parsed.text, parsed.sender);

  return { bucket, tokens };
}

/**
 * Analyze all messages in a conversation and return aggregated token usage.
 */
export function analyzeConversation(messages: any[]): ConversationTokenUsage {
  const usage: ConversationTokenUsage = {
    input: 0,
    output: 0,
    thinking: 0,
    total: 0,
    messageCount: messages.length,
  };

  for (const msg of messages) {
    const info = analyzeMessage(msg);
    if (!info) continue;
    usage[info.bucket] += info.tokens;
  }

  usage.total = usage.input + usage.output + usage.thinking;
  return usage;
}

/**
 * Aggregate multiple conversation token usages into an application total.
 * Accumulates conversation totals — does not re-tokenize individual messages.
 */
export function aggregateApplicationUsage(
  conversationUsages: ConversationTokenUsage[]
): ApplicationTokenUsage {
  const usage: ApplicationTokenUsage = {
    input: 0,
    output: 0,
    thinking: 0,
    total: 0,
    conversationCount: conversationUsages.length,
  };

  for (const convo of conversationUsages) {
    usage.input += convo.input;
    usage.output += convo.output;
    usage.thinking += convo.thinking;
  }

  usage.total = usage.input + usage.output + usage.thinking;
  return usage;
}

// ─── Formatting Utilities ────────────────────────────────────────────────────

/**
 * Format a token count with thousands separator (dot notation as in prompt spec).
 * e.g., 4820 → "4.820", 38400 → "38.400"
 */
export function formatTokenCount(count: number): string {
  if (count < 1000) return `${count}`;
  return count.toLocaleString("de-DE"); // uses dots as thousands separator
}

/**
 * Return a formatted string for display, prefixed with "~" for estimates.
 */
export function formatEstimate(count: number): string {
  return `~${formatTokenCount(count)}`;
}

/**
 * Format a bucket label for display.
 */
export function bucketLabel(bucket: "input" | "output" | "thinking"): string {
  switch (bucket) {
    case "input": return "input";
    case "output": return "output";
    case "thinking": return "thinking";
  }
}
